name: radio_tool_flutter
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/v0l/radio_tool_flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^7.1.0

ffigen:
  name: RadioToolFfi
  description: radio_tool ffi bindings
  output: 'lib/radiotool_ffi.dart'
  compiler-opts:
    - '-Iradio_tool/include'
    - '-Wno-nullability-completeness'
  headers:
    entry-points:
      - 'radio_tool/include/export.h'

flutter:
  assets:
    - 'radio_tool/build/libradiotool.dylib'
    - 'radio_tool/build/libusb-1.0.dylib'
  plugin:
    platforms:
      android:
        package: com.example.radio_tool_flutter
        pluginClass: RadioToolFlutterPlugin
      ios:
        pluginClass: RadioToolFlutterPlugin
      macos:
        pluginClass: RadioToolFlutterPlugin
      windows:
        pluginClass: RadioToolFlutterPluginCApi
      linux: 
        pluginClass: RadioToolFlutterPlugin

